### ISSUE TITLE
Pull request preview

### ISSUE THREAD

**Issue by giordano** [tlienart/xranklin-build-action#2]
Is it possible to deploy to a subdir when building for a pull request, like Documenter.jl does?  Is this what https://github.com/tlienart/xranklin-build-action/blob/1db3d0b17c2bb632bc203887bafa08580bd0f25e/action.yml#L18-L24 is for?

***Edit***: I can answer the question myself: [yes](https://github.com/JuliaParallel/juliaparallel.github.io/pull/20).

**Comment by giordano** [comment]
Related question: is it possible to build without deploying?  That'd be useful to test PRs which don't have the rights to deploy, like those opened from forks of the repository.

**Comment by tlienart** [comment]
If I understood your request properly, this is now in `@v3.3` with the `DEPLOY` toggle. It's used in the test: https://github.com/tlienart/xranklin-build-action/blob/3a1306e61184ac406250ba129f1725adb4a7c03c/.github/workflows/test.yml#L17

it blocks all actions after the build (so the build gets executed then the subsequent steps which would place the content on a dedicated branch are ignored).
